# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded logger 1.0 [list source [file join $dir logger.tcl]]
package ifneeded ruleH 1.0 [list source [file join $dir rules.tcl]]
package ifneeded runner 1.0 [list source [file join $dir runner.tcl]]
package ifneeded rulesUtils 1.0 [list source [file join $dir [file join rules utils.tcl]]]
package ifneeded rulesUtils 1.0 [list source [file join $dir [file join rules utils.tcl]]]
package ifneeded rulesGraph 1.0 [list source [file join $dir [file join rules graph.tcl]]]
